### ISSUE TITLE
Decommission this version/package?

### ISSUE THREAD

**Issue by abatishchev** [senzacionale/jwt-portable-dotnet#1]
Hi!
I'm the maintainer of the upstream, original version of Jwt.Net and was poking around NuGet.org, searched for "jwt" to see what will show up.
Your package https://www.nuget.org/packages/Portable.JWT/ aims to make it portable what's already included into the library.
I wonder if you would agree to unlist your package to consolidate the user base.
Thanks! And please feel free to contribute or reach out for anything else.

**Comment by senzacionale** [comment]
Hi. This project is not maintained for 6+ years

**Comment by abatishchev** [comment]
Yeah, I know. Please unlist the package on nuget.org. Thanks!
